#!/usr/bin/env python3
"""重组 docs/question.md：统一主题分类（≤20 类），不区分通用与项目实现。"""

from __future__ import annotations

import re
from collections import OrderedDict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
QUESTION_MD = ROOT / "docs" / "question.md"

NEW_CATEGORIES: list[str] = [
    "Agent 范式、Harness 与运行时",
    "系统架构与 Multi-Agent 设计",
    "Context、Prompt 与缓存工程",
    "结构化输出与解析",
    "记忆工程",
    "工具、Skill 与协议生态",
    "RAG 与知识检索",
    "代码修复流水线与自愈闭环",
    "运行时控制、Cancel 与 Checkpoint",
    "安全、沙箱与 Human-in-the-Loop",
    "评测、幻觉与质量保障",
    "可观测、Trace 与运维韧性",
    "性能、流式与 LLM 网关",
    "系统设计、会话与部署",
]

# (category, keywords) — 按优先级从高到低匹配，先命中先归类
TEXT_RULES: list[tuple[str, tuple[str, ...]]] = [
    (
        "记忆工程",
        (
            "Memory Engineering",
            "记忆工程",
            "记忆系统",
            "记忆管理",
            "四层 Memory",
            "四层记忆",
            "Working / Episodic",
            "Working Memory",
            "Episodic Memory",
            "Durable Memory",
            "Semantic Memory",
            "Memory Dream",
            "MEMORY.md",
            "topic.md",
            "Mem0",
            "Zep",
            "用户画像",
            "记忆写入",
            "记忆召回",
            "记忆冲突",
            "记忆遗忘",
            "记忆检索",
            "记忆压缩",
            "记忆健康",
            "similar_fixes 只作",
            "repair-precedent",
            "derive_embed_query",
            "Candidate schema",
            "Memory 和 Checkpoint",
            "Memory 写入",
            "Memory 多租户",
            "Memory 与 Context",
            "Memory 不能替代",
            "Memory 层",
            "User Memory",
            "Session Memory",
            "长期记忆",
            "短期记忆",
            "中期摘要",
            "Declarative",
            "Procedural",
            "Skill 算哪种",
            "over-personalization",
            "忘记这件事",
            "记忆",
            "Memory ",
            "/ similar_fixes",
        ),
    ),
    (
        "RAG 与知识检索",
        (
            "RAG",
            "检索增强",
            "Hybrid",
            "Rerank",
            "HyDE",
            "GraphRAG",
            "向量库",
            "向量检索",
            "embedding",
            "Embedding",
            "ripgrep",
            "BM25",
            "重排序",
            "Query Rewrite",
            "企业知识库",
            "知识库",
            "代码检索",
            "Semantic Memory 检索",
            "keyword 与 semantic 合并",
        ),
    ),
    (
        "结构化输出与解析",
        (
            "标准 JSON",
            "JSON Mode",
            "JSON 修",
            "json5",
            "SuspectList",
            "markdown 代码围栏",
            "parse 降级",
            "多级 parse",
            "regex 抽取 JSON",
            "空 SuspectList",
            "temperature 设为 0",
            "temperature / top-p",
            "Pydantic",
            "schema 校验失败",
            "typed JSON",
            "structured final",
            "JSON / dataclass",
            "外置 Prompt / YAML Skill / 多级 JSON parse",
        ),
    ),
    (
        "代码修复流水线与自愈闭环",
        (
            "Localizer",
            "Patcher",
            "Verifier",
            "Retriever",
            "RepairState",
            "run_repair",
            "repair ",
            "一次 repair",
            "patch apply",
            "Patch 太大",
            "候选补丁",
            "嫌疑文件",
            "嫌疑位置",
            "SuspectList",
            "ground truth 为什么常选 pytest",
            "ground truth 为什么是容器",
            "验证默认走 Docker",
            "验证用 Docker",
            "Single-Agent 降级",
            "degraded_mode",
            "RepairPlan",
            "终态 `fixed`",
            "终态 `patched`",
            "localize / patch / verify",
            "定位角色",
            "检索角色",
            "改码角色",
            "验证角色",
            "定位产出",
            "检索产出",
            "改码阶段",
            "验证阶段",
            "验证失败",
            "唯一写阶段",
            "写窗口单飞",
            "阶段级读写锁",
            "Agent 池化预热",
            "自愈闭环",
            "Patch 质量",
            "ImportError",
            "logic_error",
            "patcher prompt",
            "Verifier 独立 Agent",
            "Retriever 检索的是代码",
            "M5–M8",
            "similar_fixes",
            "编排器",
            "标准流水线",
            "重试环",
            "patch→verify",
            "retry_count",
            "agent_errors",
            "流程层状态",
            "流程真相",
            "四角色",
            "L2 角色",
            "L2 Agent",
            "FixLoop",
            "定位与检索",
            "改码 prompt",
            "改码+验证",
            "Planner 或 Reviewer",
            "ast/stack/git/find_test",
            "Verifier 仅暴露",
            "Patcher 注册表",
            "Localizer 注册表",
            "无 Skill 命中时，编排器",
            "Skill 的 priority",
            "复合类 Issue",
            "subtask",
        ),
    ),
    (
        "工具、Skill 与协议生态",
        (
            "Function Calling",
            "Tool Use",
            "Tool Schema",
            "Tool Loop",
            "ToolGateway",
            "Tool Routing",
            "Tool Call",
            "Tool Selection",
            "MCP",
            "A2A",
            "Skill 写",
            "Skill 怎么",
            "Skill 如何",
            "Skill 和 Tool",
            "Skill 与 Tool",
            "Skill 召回",
            "Skill 版本",
            "Skill 注入",
            "Skill 匹配",
            "Skill 的定义",
            "matched_skill",
            "suggested_tools",
            "工具描述",
            "工具注册",
            "工具白名单",
            "工具粒度",
            "工具返回",
            "工具调用",
            "工具执行",
            "工具链",
            "工具太多",
            "工具命名",
            "Observation 太长",
            "Gate 层",
            "闸口",
            "ToolExecutor",
            "九道",
            "Middleware",
            "Pre-Hook",
            "Post-Hook",
            "幻觉执行",
            "grep` 类",
            "Patch / Edit 工具",
        ),
    ),
    (
        "运行时控制、Cancel 与 Checkpoint",
        (
            "CancellationToken",
            "Cancel",
            "cancel ",
            "取消信号",
            "用户取消",
            "user_cancel",
            "checkpoint",
            "Checkpoint",
            "续跑",
            "断点续",
            "max_steps",
            "TaskState",
            "Outer Loop",
            "Run Loop",
            "暂停",
            "stopped",
            "graceful shutdown",
            "L1 逐步 checkpoint",
            "L2 阶段 checkpoint",
        ),
    ),
    (
        "安全、沙箱与 Human-in-the-Loop",
        (
            "沙箱",
            "sandbox",
            "Docker",
            "容器逃逸",
            "HITL",
            "Human-in-the-loop",
            "Human-on-the-loop",
            "Human-out-of-the-loop",
            "Gate 事前",
            "越界路径",
            "命令注入",
            "SQL 注入",
            "脱敏",
            "dry-run",
            "Dry-run",
            "prompt injection",
            "二次确认",
            "高风险工具",
            "权限网关",
            "越狱",
            "红队",
            "GDPR",
            "合规",
            "数据脱敏",
            "最小权限",
        ),
    ),
        (
        "评测、幻觉与质量保障",
        (
            "评测",
            "eval ",
            "Eval ",
            "benchmark",
            "幻觉",
            "LLM-as-judge",
            "LLM-as-Judge",
            "ground truth",
            "回归集",
            "对抗样本",
            "Precision / Recall",
            "命中率怎么测",
            "A/B",
            "eval report",
            "eval 变体",
            "质量如何保证",
            "人工抽检",
            "真 Multi-Agent」和「四个 Prompt",
            "证伪",
            "Pass@",
            "Case 库",
            "fix_rate",
            "消融",
            "holdout",
            "scaffolded",
            "by_issue_type",
            "by_difficulty",
            "min_lines.txt",
            "requires_retriever",
            "60-run",
            "统计检验",
        ),
    ),
    (
        "可观测、Trace 与运维韧性",
        (
            "Tracing",
            "trace",
            "Trace ",
            "Langfuse",
            "LangSmith",
            "Metrics",
            "RED（",
            "Saturation",
            "Runbook",
            "审计日志",
            "结构化日志",
            "采样率",
            "span",
            "run_id",
            "parent_span",
            "trace 体量",
            "trace 怎么串",
            "trace 存",
            "trace 字段",
            "落库 / trace",
            "编排全链路 trace",
        ),
    ),
    (
        "性能、流式与 LLM 网关",
        (
            "SSE",
            "WebSocket",
            "流式",
            "首 Token",
            "首 token",
            "首字",
            "latency",
            "延迟",
            "KV Cache",
            "Semantic Cache",
            "Exact Cache",
            "LLM 网关",
            "限流",
            "熔断",
            "fallback",
            "Ollama",
            "vLLM",
            "LoRA",
            "QLoRA",
            "微调",
            "连接池",
            "keep-alive",
            "反向代理",
            "RPM",
            "Token 延迟",
            "partial result",
            "streaming parser",
            "cache 命中率",
        ),
    ),
    (
        "系统设计、会话与部署",
        (
            "Session",
            "User ID",
            "多租户",
            "Redis",
            "Kafka",
            "部署",
            "runs 表",
            "events 表",
            "artifacts 表",
            "Sticky Session",
            "/health",
            "/ready",
            "K8s",
            "Worker liveness",
            "Worker readiness",
            "容量规划",
            "REST v1",
            "Idempotency",
            "幂等",
            "队列",
            "有状态 Agent",
            "无状态 Agent",
            "有状态 Worker",
            "刷新页面",
            "多设备",
            "群聊",
            "落库",
            "温池复用",
            "单 Turn 单容器",
        ),
    ),
    (
        "Context、Prompt 与缓存工程",
        (
            "Context Engineering",
            "Context、Prompt",
            "ContextManager",
            "Prompt Engineering",
            "Loop Engineering",
            "Query Expansion",
            "Query Rewrite",
            "KV Cache",
            "Semantic Cache",
            "Exact Cache",
            "Prompt Cache",
            "Prefix Cache",
            "缓存前缀",
            "Prompt 改动",
            "system prompt",
            "User Message",
            "task_template",
            "L0–L5",
            "L0-L5",
            "L5 ",
            "压缩管线",
            "压缩 epoch",
            "钉扎",
            "tier_pins",
            "prefix 段",
            "token 预算",
            "澄清问题",
            "改口",
            "主动追问",
            "八段",
            "五段组装",
            "canonical",
            "history.jsonl",
            "投影 copy",
            "summarizer",
            "issue/stack",
            "workspace section",
            "complete_once",
            "ask()",
        ),
    ),
    (
        "系统架构与 Multi-Agent 设计",
        (
            "Multi-Agent",
            "Orchestrator",
            "Orchestration",
            "Blackboard",
            "SubAgent",
            "意图识别",
            "意图路由",
            "意图体系",
            "Intent Taxonomy",
            "Slot Filling",
            "Fan-out",
            "Fan-in",
            "Map-Reduce",
            "Choreography",
            "LangGraph",
            "状态机",
            "DAG ",
            "Layer 1",
            "Layer 2",
            "agent_runtime",
            "FixLoop 解决",
            "FixLoop 与",
            "FixLoop 中",
            "FixLoop 泛化",
            "四个 Agent",
            "四个 Prompt",
            "四个 L2",
            "四个角色",
            "dataclass 协议",
            "dataclass /",
            "Blackboard 架构",
            "消息总线",
            "共享状态板",
            "Todolist",
            "Planner 角色",
            "路由到不存在",
            "并行意图",
            "串行意图",
            "动态路由",
            "自研运行时",
            "LangChain / LangGraph",
            "标准库零依赖",
            "M{m}/D{d}",
            "工厂创建多个实例",
            "ReAct 循环为何放在 Layer 1",
        ),
    ),
]


def route_by_text(text: str) -> str:
    lower = text.lower()
    for cat, keywords in TEXT_RULES:
        if any(k.lower() in lower for k in keywords):
            return cat
    return "Agent 范式、Harness 与运行时"


def parse_questions(content: str) -> list[str]:
    """提取全部题目正文（忽略当前分类标题）。"""
    items: list[str] = []
    current_cat = ""
    for line in content.splitlines():
        m_cat = re.match(r"^-\s+(.+)$", line)
        if m_cat and not re.match(r"^\d+\.", m_cat.group(1).strip()):
            title = m_cat.group(1).strip()
            if title and not title.startswith("**") and "题" not in title[:6]:
                current_cat = title
            continue
        m_q = re.match(r"^\s+(\d+)\.\s+(.+)$", line)
        if m_q and current_cat:
            items.append(m_q.group(2).strip())
    return items


def build_markdown(buckets: OrderedDict[str, list[str]]) -> str:
    total = sum(len(v) for v in buckets.values())
    n_cat = len(buckets)
    lines = [
        f"# Agent 面试题库（{n_cat} 类）",
        "",
        f"> 统一主题分类（不区分通用概念与项目实现）；共 **{n_cat} 类**，≤20 类上限。",
        "",
        f"> **总题量：{total} 题**",
        "",
        "## 目录",
        "",
    ]
    for i, (cat, qs) in enumerate(buckets.items(), 1):
        lines.append(f"{i}. **{cat}**（{len(qs)} 题）")
    lines.extend(["", "---", ""])
    for cat, qs in buckets.items():
        lines.append(f"- {cat}")
        for j, q in enumerate(qs, 1):
            lines.append(f"    {j}. {q}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    content = QUESTION_MD.read_text(encoding="utf-8")
    questions = parse_questions(content)
    if not questions:
        raise SystemExit("未解析到任何题目")

    buckets: OrderedDict[str, list[str]] = OrderedDict(
        (cat, []) for cat in NEW_CATEGORIES
    )
    for text in questions:
        cat = route_by_text(text)
        buckets[cat].append(text)

    buckets = OrderedDict((k, v) for k, v in buckets.items() if v)

    out = build_markdown(buckets)
    QUESTION_MD.write_text(out, encoding="utf-8")
    print(f"Wrote {QUESTION_MD} — {len(questions)} questions, {len(buckets)} categories")
    for cat, qs in buckets.items():
        print(f"  {cat}: {len(qs)}")


if __name__ == "__main__":
    main()
